site_name: Ghostwriter Docs
theme:
  name: 'material'
markdown_extensions:
- codehilite
nav:
  - 'Introduction': 'index.md'
  - 'How it works': 'overview.md'
  #- 'Getting Started': 'getting_started.md'
  - 'Why generate code?': 'why.md'
  - 'Design Choices': 'design_choices.md'
  - Manual:
    # - 'user_overview.md'
    - 'configuration.md'
    - 'snippets.md'
    - 'template_dsl.md'
    - 'writer.md'
    # - 'specs.md'
