site_name: Ghostwriter Docs
theme:
  name: 'material'
markdown_extensions:
- codehilite
nav:
  - 'Introduction': 'index.md'
  - 'Motivation': 'motivation.md'
  - 'When to generate code?': 'when.md'

  - 'Design Choices': 'design_choices.md'
  - Manual:
    # - 'user_overview.md'
    - 'configuration.md'
    - 'template_dsl.md'
    - 'snippets.md'
    # - 'writer.md' -- expose later, possibly refined
    # - 'specs.md'
